FROM alpine:latest
ENV interactionless=true
ENV ROOT_PASSWORD=oneclick136
RUN apk update && \
    apk add --no-cache \
    openssh \
    curl \
    wget \
    bash \
    dos2unix \
    vim \
    htop \
    procps \
    dcron
RUN echo "Related repo https://github.com/oneclickvirt/docker" >> /etc/banner || true
RUN echo "--by https://t.me/spiritlhl" >> /etc/motd || true
RUN echo "Related repo https://github.com/oneclickvirt/docker" >> /etc/banner || true
RUN echo "--by https://t.me/spiritlhl" >> /etc/banner || true
RUN ssh-keygen -A
RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config && \
    sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config && \
    sed -i 's/UsePAM yes/UsePAM no/' /etc/ssh/sshd_config
RUN wget https://raw.githubusercontent.com/oneclickvirt/docker/refs/heads/main/scripts/ssh_sh.sh -O /ssh_sh.sh && \
    chmod +x /ssh_sh.sh && \
    sh /ssh_sh.sh $ROOT_PASSWORD
RUN printf '#!/bin/sh\n\
/usr/sbin/sshd\n\
crond\n\
if [ "$IPV6_ENABLED" = "true" ]; then\n\
  echo "*/1 * * * * curl -m 6 -s ipv6.ip.sb && curl -m 6 -s ipv6.ip.sb" | crontab -\n\
fi\n\
tail -f /dev/null\n' > /start.sh && \
    chmod +x /start.sh
EXPOSE 22
CMD ["/start.sh"]
