FROM rockylinux/rockylinux:latest
ENV DEBIAN_FRONTEND=noninteractive
ENV interactionless=true
ENV ROOT_PASSWORD=oneclick136
RUN dnf -y update && \
    dnf install -y --skip-broken \
    openssh-server \
    curl \
    wget \
    cronie \
    lsof \
    dos2unix \
    vim \
    nano \
    net-tools
RUN echo "Related repo https://github.com/oneclickvirt/docker" >> /etc/banner || true
RUN echo "--by https://t.me/spiritlhl" >> /etc/motd || true
RUN echo "Related repo https://github.com/oneclickvirt/docker" >> /etc/banner || true
RUN echo "--by https://t.me/spiritlhl" >> /etc/banner || true
RUN mkdir /var/run/sshd
RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config && \
    sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config && \
    sed -i 's/UsePAM yes/UsePAM no/' /etc/ssh/sshd_config
# RUN wget https://raw.githubusercontent.com/gdraheim/docker-systemctl-replacement/master/files/docker/systemctl3.py -O /bin/systemctl && \
#     chmod a+x /bin/systemctl
RUN wget https://raw.githubusercontent.com/oneclickvirt/docker/refs/heads/main/scripts/ssh_bash.sh -O ssh_bash.sh && \
    chmod +x ssh_bash.sh && \
    bash ssh_bash.sh $ROOT_PASSWORD
RUN printf '#!/bin/bash\n\
service ssh start\n\
if [ "$IPV6_ENABLED" = "true" ]; then\n\
  echo "*/1 * * * * curl -m 6 -s ipv6.ip.sb && curl -m 6 -s ipv6.ip.sb" | crontab -\n\
fi\n\
tail -f /dev/null\n' > /start.sh && \
chmod +x /start.sh
EXPOSE 22
CMD ["/start.sh"]
